# Generated by Django 2.2.6 on 2019-11-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(choices=[('g', 'Großkatzen'), ('kk', 'Kleinkatzen'), ('p', 'Primaten'), ('h', 'Hunde'), ('k', 'Kamele'), ('b', 'Großbären'), ('pf', 'Pferde')], max_length=1)),
                ('category', models.CharField(choices=[('l', 'Löwe'), ('p', 'Puma'), ('a', 'Affe'), ('w', 'Wolf'), ('t', 'Trampeltier'), ('e', 'Esel'), ('le', 'Leopard'), ('lu', 'Luchs'), ('b', 'Braunbär')], max_length=1)),
                ('name', models.TextField()),
                ('origin_land', models.TextField(blank=True)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('food', models.TextField()),
                ('zoo', models.TextField()),
                ('zookeeper', models.TextField(blank=True)),
            ],
        ),
    ]
