# Generated by Django 2.2.6 on 2019-11-08 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('postal_code', models.TextField()),
                ('town', models.TextField()),
                ('land', models.TextField()),
                ('telephone_number', models.TextField(blank=True)),
                ('mail', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zookeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('date_of_birth', models.DateField(blank=True)),
                ('adjusted_since', models.DateField()),
                ('salary', models.IntegerField()),
                ('telephone_number', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(choices=[('gk', 'Großkatzen'), ('kk', 'Kleinkatzen'), ('p', 'Primaten'), ('h', 'Hunde'), ('k', 'Kamele'), ('gb', 'Großbären'), ('pf', 'Pferde')], max_length=2)),
                ('category', models.CharField(choices=[('l', 'Löwe'), ('p', 'Puma'), ('a', 'Affe'), ('w', 'Wolf'), ('tt', 'Trampeltier'), ('e', 'Esel'), ('le', 'Leopard'), ('lu', 'Luchs'), ('b', 'Braunbär')], max_length=2)),
                ('name', models.TextField()),
                ('origin_land', models.TextField(blank=True)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('food', models.TextField()),
                ('zoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework_one_kahr.Zoo')),
                ('zookeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework_one_kahr.Zookeeper')),
            ],
        ),
    ]
